### ISSUE TITLE
Issue on Windows 11

### ISSUE THREAD

**Issue by dillfrescott** [dennis-tra/pcp#28]
```
Calculating on key information...panic: crypto/elliptic: Add was called on an invalid point

goroutine 7213 [running]:
crypto/elliptic.(*nistCurve[...]).Add(0x15cb340?, 0xa3b9d2, 0x68?, 0x11680a0?, 0xc00102c201?)
        C:/Program Files/Go/src/crypto/elliptic/nistec.go:181 +0xb5
github.com/schollz/pake/v2.(*Pake).Update(0xc0011ac360, {0xc001ec2000, 0x645, 0x645})
        C:/Users/micro/go/pkg/mod/github.com/schollz/pake/v2@v2.0.6/pake.go:236 +0xbd7
github.com/dennis-tra/pcp/pkg/node.(*PakeProtocol).StartKeyExchange(0xc0000e02a0, {0x15bed78, 0xc00008ccd0}, {0xc00141c0c0, 0x27})
        C:/Users/micro/Downloads/pcp/pkg/node/pake.go:250 +0x357
github.com/dennis-tra/pcp/pkg/receive.(*Node).HandlePeer(0xc00063c990, {{0xc00141c0c0, 0x27}, {0xc001944b10, 0x1, 0x1}})
        C:/Users/micro/Downloads/pcp/pkg/receive/node.go:157 +0x525
created by github.com/dennis-tra/pcp/pkg/mdns.(*Discoverer).drainEntriesChan
        C:/Users/micro/Downloads/pcp/pkg/mdns/discoverer.go:82 +0x29b
```

Any ideas on how to solve this?

**Comment by q9f** [comment]
Having the same issue on Archlinux `pcp version vdev+5f3759df`

```
Calculating on key information...panic: crypto/elliptic: Add was called on an invalid point                                                                                                                                                    

goroutine 10301 [running]:
crypto/elliptic.(*nistCurve[...]).Add(0xf84c80?, 0x452709, 0x68?, 0xb1fc00?, 0x1?)
	/usr/lib/go/src/crypto/elliptic/nistec.go:181 +0xaa
github.com/schollz/pake/v2.(*Pake).Update(0xc001708360, {0xc001714000, 0x4c4, 0x4c4})
	/home/user/.go/pkg/mod/github.com/schollz/pake/v2@v2.0.6/pake.go:206 +0x5c2
github.com/dennis-tra/pcp/pkg/node.(*PakeProtocol).onKeyExchange(0xc000262000, {0xf80400?, 0xc00468a1c0})
	/home/user/.go/pkg/mod/github.com/dennis-tra/pcp@v0.4.0/pkg/node/pake.go:135 +0x2c5
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc0029c4120, 0xf}, {0x7f2e2a700fb0?, 0xc00468a1c0})
	/home/user/.go/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:566 +0x6b
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler in goroutine 10414
	/home/user/.go/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:416 +0x6be
```

**Comment by SerJaimeLannister** [comment]
any updates on this ? (I am also on archlinux)
