### ISSUE TITLE
Weird crash on macOS 13.5.2, go 1.21.1

### ISSUE THREAD

**Issue by theovosse** [dennis-tra/pcp#29]
In installed it under macos 13.5.2, go 1.21.1 with the command "go install github.com/dennis-tra/pcp/cmd/pcp@latest", and ran it like this:

$ pcp send db-pids.txt

The output was 

Code is:  w1-w2-w3-w4
On the other machine run:
	pcp receive w1-w2-w3-w4
runtime: g85: frame.sp=0xc0001c36b8 top=0xc0001c3fe0
	stack=[0xc0001c2000-0xc0001c4000
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw({0x19499ad?, 0x0?})
	/usr/local/go/src/runtime/panic.go:1077 +0x5c fp=0x700011bd49d8 sp=0x700011bd49a8 pc=0x1038e1c
runtime.(*unwinder).finishInternal(0x0?)
	/usr/local/go/src/runtime/traceback.go:561 +0x12a fp=0x700011bd4a18 sp=0x700011bd49d8 pc=0x105d76a
runtime.(*unwinder).next(0x700011bd4c18?)
	/usr/local/go/src/runtime/traceback.go:442 +0x232 fp=0x700011bd4a90 sp=0x700011bd4a18 pc=0x105d572
runtime.copystack(0xc00018b6c0, 0x800000002?)
	/usr/local/go/src/runtime/stack.go:934 +0x2d2 fp=0x700011bd4d88 sp=0x700011bd4a90 pc=0x10522d2
runtime.newstack()
	/usr/local/go/src/runtime/stack.go:1116 +0x47f fp=0x700011bd4f38 sp=0x700011bd4d88 pc=0x105287f
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:593 +0x8f fp=0x700011bd4f40 sp=0x700011bd4f38 pc=0x1069f6f

goroutine 85 [copystack]:
github.com/minio/sha256-simd.blockAvx2({0xc0001c36f0, 0x8, 0x8}, {0xc0001c3778, 0x40, 0x40})
	/Users/theo/work/go/pkg/mod/github.com/minio/sha256-simd@v0.1.1/sha256blockAvx2_amd64.s:125 +0x1423 fp=0xc0001c36c0 sp=0xc0001c36b8 pc=0x11d7dc3
created by github.com/libp2p/go-libp2p-kad-dht/rtrefresh.(*RtRefreshManager).Start in goroutine 105
	/Users/theo/work/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.11.1/rtrefresh/rt_refresh_manager.go:88 +0x65

Plus a lot more stacks.

**Comment by theovosse** [comment]
w1-w2-w3-w4 is of course not the printed info.
